In [8]:
import numpy as np

a1 = np.array([[1,2,3], [10,20,30]])
print(a1)#2차원배열
print(a1.ndim)#해당 array는 몇차원?
print(a1.shape)#각 차원의 원소 개수(2차원의 원소 : 2 / 1차원 원소: 3)
print(a1.size)#모든 원소 개수

[[ 1  2  3]
 [10 20 30]]
2
(2, 3)
6


### reshape 
* 1차원 배열을 다차원 배열로 만들어줌
* 개수가 맞아 떨어져아한다. 아닐 시 ValueError

In [15]:
a2 = np.arange(20).reshape(4,5) #0부터 19까지 원소5개인 배열 4개!
print(a2)
print(a2.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


### flatten / ravel
* 다차원 배열을 1차원 배열로 만들어줌

* flatten => 깊은복사(주소다름)   -   주로사용
* ravel => 얕은복사(주소같음)

In [21]:
a3 = a2.flatten() #2차원이든 3차원이든 다시 1차원배열로 만들어줌
a3[3] = 100
print(a3)
print(a2)


a4 = a2.ravel()
a4[3] = 200
print(a4)
print(a2)

[  0   1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]
[  0   1   2 200   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]
[[  0   1   2 200   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]]


### 다차원배열 index로 확인
* print(a2[:, 1]) : [1차원 배열은 전부!, 원소는 1번index만!]
* print(a2[:, 1:4]) : [1차원 배열은 전부!, 1번start : 4번 stop!]
* print(a2[:, 1:4:2]) : [1차원 배열은 전부!, 1번start : 4번 stop! : 2개씩 step!]
* print(a2[::2, :]) : [start,stop 안줌!(전부다) : 2개씩 stop, 전부다]<br><br>

* print(a2[행:열])

In [43]:
a2 = np.arange(20).reshape(4,5)
print(a2)
# print(a2[1,2])

# print(a2[:, 1])
# print(a2[:, 1:4])
# print(a2[:, 1:4:2])
# print(a2[1:3, :])
# print(a2[::2, :])
print(a2[::2, 1:4])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[3 4]
 [8 9]]


### axis
*axis = 0 은 세로축.<br><br>
print(a2.sum(axis=0)) : 세로축으로 다 더해라<br>
print(a2.sum(axis=1)) : 가로축으로 다 더해라


In [53]:
print(a2)
print(a2.shape)
print(a2.sum())
# print(a2.sum(axis=0))
print(a2.sum(axis=1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
190
[10 35 60 85]


### T => axis가 2개일때 보통 사용?<br>
a3 = a2.T => 가로축과 세로축을 서로 바꿔라

In [58]:
print(a2, a2.shape)
print()
a3 = a2.T
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


### moveaxis => T와 같음 사용방법 다름

In [129]:
print(a2, a2.shape)
print()
a3 = np.moveaxis(a2, [0], [1])
print(a3, a3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (4, 5)

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]] (5, 4)


In [87]:
a10 = np.arange(5, 20).reshape(3,5)

# a11 = a10.reshape(3,5)
print(a10, a10.shape)
print()

#shape 3,5의 2차원 ndarray로 만들기.
print(a10[:, 2:4])

print()

print(a10[:, 2:4].sum(axis=0))

a11 = a10[:, 2:4]
print(a11.sum(axis=0))


[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] (3, 5)

[[ 7  8]
 [12 13]
 [17 18]]

[36 39]
[36 39]


### np.mean(a, axis=none):axis의 축에 따라 평균이 구해짐


In [88]:
print(np.mean(a11)) #전체 숫자의 평균
print(np.mean(a11, axis=0)) #axis=?의 축의 평균

12.5
[12. 13.]


### np.concatenate((a,b)) : ndarray합치기
* axis에따라 어떤방향으로 붙일지 정할 수 있음. (1 : 가로/ 2 : 세로)

In [101]:
a1 = np.arange(0,10).reshape(2,5)
a2 = np.arange(100,110).reshape(2,5)
print(a1)
print(a2)
print()
a3 = np.concatenate((a1,a2), axis=1) #tuple로 감싸야됨
print(a3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100 101 102 103 104]
 [105 106 107 108 109]]

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]


### np.hstack((a,b)) : 가로로 붙이기/ axis = 1
### np.vstack((a,b)) : 세로로 붙이기/axis=0


In [108]:
a4 = np.hstack((a1,a2))
print(a4)
a5 = np.vstack((a1,a2))
print(a4)

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]
[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]


### np.hsplit(a, 조각개수) : 가로로 조각 개수만큼 잘라라

In [113]:
print(a4)
a6 = np.hsplit(a4, 5) 
print()
print(a6)

[[  0   1   2   3   4 100 101 102 103 104]
 [  5   6   7   8   9 105 106 107 108 109]]

[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[  4, 100],
       [  9, 105]]), array([[101, 102],
       [106, 107]]), array([[103, 104],
       [108, 109]])]


### np.vsplit(a, 조각개수):세로로 조각 개수만큼 잘라라


In [128]:
a7 = a4.T
print(a7)
a8 = np.vsplit(a7, 5)
print(a8)

[[  0   5]
 [  1   6]
 [  2   7]
 [  3   8]
 [  4   9]
 [100 105]
 [101 106]
 [102 107]
 [103 108]
 [104 109]]
[array([[0, 5],
       [1, 6]]), array([[2, 7],
       [3, 8]]), array([[  4,   9],
       [100, 105]]), array([[101, 106],
       [102, 107]]), array([[103, 108],
       [104, 109]])]


### bool list : 필터적용.
* a2[:, 0]%10==5 : a2에 나머지가 5인 배열을 필터링 해서 가져와라

In [127]:
a2 = np.arange(20).reshape(4,5)
print(a2)
# myfilter1 = a2[a2%10==5]
filter1 = a2[:, 0]%10==5
print(a2[filter1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
