<style>
div.text_cell_render {
    font-family: "D2Coding";
    font-size: 12pt;
    line-height: 1.5;
}
</style>

<style>
div.text_cell_render {
    font-family: "D2Coding";
    font-size: 12pt;
    line-height: 1.5;
}
</style>

In [22]:
import numpy as np

a1 = np.arange(30).reshape(5,6)
print(a1)
print('np.sum: ', np.sum(a1, axis=1))
# print(np.add.reduce(a1, axis=1, where=a1%2==0)) #where : 짝수만 합계를 구함
# default로 axix = 0이 잡혀있음.
#reduce : for문 돌아줄게~
# print(np.add.accumulate(a1, axis=0))
# print(np.add.reduceat(a1, [0,2,4], axis=1))
print(np.add.at(a1, [0,2,4], [10,20,30,40,50,60]))
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
np.sum:  [ 15  51  87 123 159]
None
[[10 21 32 43 54 65]
 [ 6  7  8  9 10 11]
 [22 33 44 55 66 77]
 [18 19 20 21 22 23]
 [34 45 56 67 78 89]]


In [23]:
a2 = np.arange(10)
a3 =np.arange(100,110)
print(a2)
print(a3)
print(np.add.outer(a2,a3))

[0 1 2 3 4 5 6 7 8 9]
[100 101 102 103 104 105 106 107 108 109]
[[100 101 102 103 104 105 106 107 108 109]
 [101 102 103 104 105 106 107 108 109 110]
 [102 103 104 105 106 107 108 109 110 111]
 [103 104 105 106 107 108 109 110 111 112]
 [104 105 106 107 108 109 110 111 112 113]
 [105 106 107 108 109 110 111 112 113 114]
 [106 107 108 109 110 111 112 113 114 115]
 [107 108 109 110 111 112 113 114 115 116]
 [108 109 110 111 112 113 114 115 116 117]
 [109 110 111 112 113 114 115 116 117 118]]
